### ISSUE TITLE
UML 

### ISSUE THREAD

**Issue by SebChw** [SebChw/JavaJsonTools#3]
Put here all of yours ideas while creating some UML diagrams and ask all questions you have during writing it you can ask guys responsible for other issues questions instead learning it by yourself

**Comment by LucasLechevestrier** [comment]
<img width="599" alt="first_diagram_class" src="https://user-images.githubusercontent.com/101550799/165803116-46cadbf5-0f30-4d85-a440-48250c5263d2.png">

**Comment by LucasLechevestrier** [comment]
[test_interface.zip](https://github.com/SebChw/JavaJsonTools/files/8584725/test_interface.zip)
Dirty implementation of the diagram above

**Comment by LucasLechevestrier** [comment]
[class_diagram.zip](https://github.com/SebChw/JavaJsonTools/files/8584734/class_diagram.zip)
A modifiable version of the diagram bove

**Comment by SebChw** [comment]
![JSONToolsUML](https://user-images.githubusercontent.com/66476124/167162891-2cce029b-7131-4b40-bc21-5a238877cc6d.png)

**Comment by SebChw** [comment]
This is what we have done. We highly were inspired by this https://refactoring.guru/design-patterns/decorator. Here is brief explanation:
- JsonReader is a Concrete component it expects to get some kind of JSON representation (I am not sure what this will be, depends on what Stachu will do with the SPRING) and then return some kind of jackson JSON object.
- Every Decorator in the first line of it parse uses parse method of it's wrappee to get JSON to be modified
- In the selector we set which keys we want to filter and reverse flag means either to choose only selected or reject selected.
- We also separated Comparator from everything as it seems to behave differently than the others. It accepts any kind of filter so we can compare filtered JSONS etc.

`Please write if this seems correct for you and is understandable`

**Comment by LucasLechevestrier** [comment]
<img width="500" alt="sequence_diagram" src="https://user-images.githubusercontent.com/101550799/167167102-4f280fde-63d1-4cb0-ae69-60df8cb015d4.png">

**Comment by kapiblue** [comment]
Thank you guys. For now it seems pretty clear. I will follow the implementation guidelines from refactoring guru.
